import type { CefrLevel, RoadmapSkill, SyllabusCategory } from "@prisma/client";

export interface DefaultSyllabusItem {
  level: CefrLevel;
  category: SyllabusCategory;
  /** one of the 6 core skills this content drills */
  skill: RoadmapSkill;
  /** topic heading the subtopic is grouped under */
  theme: string;
  /** the subtopic itself — one concrete, checkable thing to master */
  title: string;
  description?: string;
}

/**
 * Bump when DEFAULT_SYLLABUS_ITEMS changes shape or content. Users on an
 * older version get reseeded on their next syllabus load; completions are
 * preserved by (level, normalized title) match.
 *
 * v3: added the "Alphabet & pronunciation" item below — the roadmap's Week 1
 * grammar slot referenced this topic before the syllabus/roadmap merge but
 * had no syllabus counterpart to link to. Any bump here must ship with a
 * paired ROADMAP_VERSION bump in roadmap-defaults.ts, since grammar/vocab
 * roadmap content is now generated FROM this list, not hand-authored.
 *
 * v4: added `skill` to every item (grammar/vocab/listening/speaking/writing/
 * reading) — no title/level changes, so this reseed is a pure metadata
 * backfill and preserves every user's completion state. Paired
 * ROADMAP_VERSION bump ships alongside for the same reason as v3.
 *
 * v5: greatly expanded the `category: "skill"` pool (speaking/writing/
 * listening/reading) — from ~10 items/level to ~21-24/level — so the roadmap
 * generator has enough distinct, syllabus-aligned topics to vary these tasks
 * day-to-day instead of repeating one hand-authored topic all week (see
 * roadmap-generator.ts's deriveDailySkillTasks). New topics are thematically
 * anchored to each phase's existing week themes/grammar/vocab so they
 * reinforce the same curriculum rather than diverging from it. Existing
 * titles are untouched, so this reseed only adds new incomplete items — no
 * completion state is at risk. Paired ROADMAP_VERSION bump ships alongside.
 */
export const SYLLABUS_VERSION = 5;

/**
 * The 2027 syllabus: full CEFR A1–B1 topic/subtopic map aligned with the
 * Goethe-Institut curricula. Grouped by theme within each level+category;
 * array order is pedagogical order — array index becomes sortOrder and "next
 * up" is the first incomplete item.
 */
export const DEFAULT_SYLLABUS_ITEMS: DefaultSyllabusItem[] = [
  // ════════════════════ A1 ════════════════════
  // ── grammar ──
  { level: "a1", category: "grammar", skill: "grammar", theme: "Alphabet & pronunciation", title: "The German alphabet & sound system", description: "Letters, umlauts, ß, and how German spelling maps to sound." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Verbs: present tense", title: "sein & haben", description: "The two anchor verbs, all persons." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Verbs: present tense", title: "Regular conjugation", description: "Stem + endings: wohnen, lernen, machen, kommen." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Verbs: present tense", title: "Stem-changing verbs", description: "e→i/ie (sprechen, lesen), a→ä (fahren, schlafen)." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Verbs: present tense", title: "wissen & möchten", description: "Irregular presents you meet constantly." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Nouns & articles", title: "Gender: der / die / das", description: "Learning every noun with its article; common gender clues (-ung, -chen…)." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Nouns & articles", title: "Indefinite articles: ein / eine", description: "And when German uses no article at all." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Nouns & articles", title: "Plural forms", description: "-e, -en, -er, -s, umlaut patterns." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Nouns & articles", title: "Negation with kein / keine", description: "kein for nouns vs. nicht for everything else." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Cases: nominative & accusative", title: "Nominative: the subject case", description: "Wer oder was macht etwas?" },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Cases: nominative & accusative", title: "Accusative articles: den / einen", description: "Only masculine changes." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Cases: nominative & accusative", title: "Accusative pronouns", description: "mich, dich, ihn, sie, es, uns, euch." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Pronouns & possessives", title: "Personal pronouns", description: "ich/du/er/sie/es/wir/ihr/sie/Sie; du vs. Sie." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Pronouns & possessives", title: "Possessive articles", description: "mein, dein, sein, ihr, unser, euer + endings." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Sentence structure", title: "Verb in second position", description: "Statements, incl. time-first: Heute lerne ich Deutsch." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Sentence structure", title: "Yes/no questions", description: "Verb first: Kommst du mit?" },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Sentence structure", title: "W-questions", description: "wer, was, wo, woher, wohin, wann, wie, warum." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Sentence structure", title: "Position of nicht", description: "Ich komme nicht. / Ich komme heute nicht mit." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Modal verbs", title: "können, müssen, möchten", description: "Meaning + conjugation." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Modal verbs", title: "dürfen, wollen, sollen", description: "Permission, intention, advice." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Modal verbs", title: "The sentence bracket", description: "Modal in position 2, infinitive at the end." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Separable verbs", title: "Common separable verbs", description: "aufstehen, einkaufen, anrufen, fernsehen, mitkommen." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Separable verbs", title: "Prefix to the end", description: "Ich stehe um 6 Uhr auf." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Imperative", title: "Sie-imperative", description: "Kommen Sie bitte mit!" },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Imperative", title: "du- and ihr-imperative", description: "Komm! / Kommt! — incl. irregular forms (Nimm!, Lies!)." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Prepositions", title: "Time: am, um, im, von … bis", description: "am Montag, um 8 Uhr, im Mai." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Prepositions", title: "Place: in, aus, nach, bei, zu", description: "Wohnort, Herkunft, Ziel." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Prepositions", title: "mit & für", description: "mit dem Bus, für dich." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Past tense (intro)", title: "Perfekt with haben", description: "Ich habe gemacht / gekauft / gelernt." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Past tense (intro)", title: "Perfekt with sein", description: "Ich bin gefahren / gegangen / geblieben." },
  { level: "a1", category: "grammar", skill: "grammar", theme: "Past tense (intro)", title: "war & hatte", description: "The Präteritum you need at A1." },

  // ── vocab themes ──
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Personal world", title: "Introducing yourself", description: "Name, Alter, Herkunft, Wohnort, Beruf, Sprachen." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Personal world", title: "Family", description: "Eltern, Geschwister, Großeltern, Familienstand." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Personal world", title: "Countries, nationalities & languages", description: "Ich komme aus …, ich spreche …" },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Numbers, time & dates", title: "Numbers 0–1000", description: "Prices, phone numbers, addresses." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Numbers, time & dates", title: "Telling the time", description: "Official + colloquial (halb acht, Viertel vor…)." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Numbers, time & dates", title: "Days, months & seasons", description: "Plus am/im for dates and Wann-questions." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Everyday life", title: "Daily routine", description: "aufstehen, frühstücken, arbeiten, schlafen gehen." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Everyday life", title: "Food & drink", description: "Lebensmittel, Mahlzeiten, im Café bestellen." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Everyday life", title: "Shopping & prices", description: "Supermarkt, Mengen, bezahlen, Was kostet…?" },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Everyday life", title: "Clothing & colors", description: "Kleidung, Größen, Farben." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Living", title: "Home & rooms", description: "Wohnung, Zimmer, Adresse." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Living", title: "Furniture & household", description: "Möbel, Geräte, Alltagsgegenstände." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Out & about", title: "Places in the city", description: "Bahnhof, Apotheke, Bank, Supermarkt, Post." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Out & about", title: "Directions", description: "links, rechts, geradeaus, weit, zu Fuß." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Out & about", title: "Transport & travel", description: "Zug, Bus, Ticket, Gleis, Fahrplan, Abfahrt." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Out & about", title: "Weather & seasons", description: "Es regnet/schneit, sonnig, kalt, warm." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Work & free time", title: "Professions", description: "Berufe + Was sind Sie von Beruf?" },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Work & free time", title: "Hobbies & free time", description: "Sport, Musik, lesen, reisen, Verabredungen." },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Health (basics)", title: "Body parts", description: "Kopf, Bauch, Rücken…" },
  { level: "a1", category: "vocab_theme", skill: "vocab", theme: "Health (basics)", title: "Saying what hurts", description: "Ich habe Kopfschmerzen / Fieber; beim Arzt." },

  // ── skills ──
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Introduce yourself fluently", description: "60 seconds about yourself without notes." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Order in a café or restaurant", description: "Bestellen, bitten, bezahlen." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Handle a shopping dialogue", description: "Nach Preis, Größe, Ort fragen." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Make and change appointments", description: "Termine vereinbaren, Uhrzeiten verstehen." },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Fill in official forms", description: "Anmeldeformulare: Name, Adresse, Geburtsdatum." },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Short messages & postcards", description: "Anrede, 2–3 Sätze, Gruß." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Announcements & signs", description: "Bahnhofsdurchsagen, Schilder, Aushänge." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Short everyday dialogues", description: "Hauptinformation aus Alltagsgesprächen." },
  { level: "a1", category: "skill", skill: "reading", theme: "Exam prep", title: "Goethe A1 task types", description: "Know every Hören/Lesen/Schreiben/Sprechen part." },
  { level: "a1", category: "skill", skill: "writing", theme: "Exam prep", title: "One full A1 Modellsatz", description: "Under exam timing." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your family", description: "Eltern, Geschwister, Familienstand." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Describe your daily routine", description: "aufstehen, frühstücken, arbeiten, ins Bett gehen." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss your hobbies and free time", description: "Was machst du gern in deiner Freizeit?" },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Ask for and give directions", description: "links, rechts, geradeaus — den Weg erklären." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about the weather", description: "Es regnet, es ist sonnig, es ist kalt." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Describe your home", description: "Zimmer, Möbel, Adresse." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your job or studies", description: "Was machst du beruflich? Was studierst du?" },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Buy a train or bus ticket", description: "Einmal nach …, bitte; Gleis, Abfahrt." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Give your phone number and address", description: "Zahlen und Adressen laut vorlesen." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Small talk about where you're from", description: "Woher kommst du? Wie lange lebst du schon hier?" },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Describe what you did yesterday", description: "Gestern habe ich … / bin ich …" },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your weekend plans", description: "Ich möchte … / Ich muss …" },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Say what you can, must and want to do", description: "können, müssen, möchten in eigenen Sätzen." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Describe symptoms at the doctor's", description: "Ich habe … Schmerzen; mir ist schlecht." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about clothes and colors you like", description: "Ich trage gern … in … Farbe." },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Ask someone about their daily routine", description: "Wann stehst du auf? Was machst du dann?" },
  { level: "a1", category: "skill", skill: "speaking", theme: "Speaking", title: "Introduce a family member to someone", description: "Das ist mein/e …; er/sie ist …" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a short self-introduction", description: "Name, Alter, Herkunft, Beruf — 3-4 Sätze." },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write about your daily routine", description: "Use time expressions: zuerst, dann, danach." },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a shopping list with quantities", description: "zwei Kilo Äpfel, ein Liter Milch…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a short note about your family", description: "Wer gehört zu deiner Familie?" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Describe your home in a few sentences", description: "Zimmer, Möbel, was dir gefällt." },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write your weekly schedule", description: "Montag habe ich …, am Dienstag …" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a short weather report", description: "Heute ist es … Morgen wird es …" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write directions to your home", description: "Geh geradeaus, dann links…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write about your hobbies", description: "Ich spiele/lese/reise gern, weil…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a short diary entry about yesterday", description: "Practice Perfekt: Ich habe/bin…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a short email requesting an appointment", description: "Ich möchte einen Termin…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a birthday or greeting card", description: "Liebe/r …, alles Gute…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "List your favorite foods and drinks", description: "Mein Lieblingsessen ist…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a note explaining you feel sick", description: "Ich fühle mich nicht gut, weil…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a short text about your job or studies", description: "Ich arbeite als … / Ich studiere…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write about what you did last weekend", description: "Am Wochenende habe ich…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write a short text describing a family photo", description: "Auf dem Foto sieht man…" },
  { level: "a1", category: "skill", skill: "writing", theme: "Writing", title: "Write 5 sentences about your day using separable verbs", description: "aufstehen, einkaufen, fernsehen…" },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone introducing themselves", description: "Name, Herkunft, Beruf — die Hauptinfos verstehen." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a family conversation", description: "Wer gehört zur Familie?" },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to numbers and prices being read aloud", description: "Preise und Telefonnummern erfassen." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to the time being announced", description: "Uhrzeiten, offiziell und umgangssprachlich." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a weather forecast", description: "Wetterbericht — Temperatur, Regen, Sonne." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a supermarket conversation", description: "Was wird gekauft? Wie viel kostet es?" },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone ordering in a café", description: "Bestellung, Preis, Bezahlung verstehen." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to directions being given", description: "links, rechts, geradeaus — den Weg verstehen." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a conversation about hobbies", description: "Was machen die Sprecher gern?" },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone describing their home", description: "Zimmer, Lage, Möbel." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone talking about their job", description: "Beruf und Arbeitsort verstehen." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a doctor's appointment being booked", description: "Datum, Uhrzeit, Grund des Termins." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a conversation about clothes shopping", description: "Größe, Farbe, Preis." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a simple story about yesterday", description: "Perfekt-Formen im Kontext erkennen." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a conversation about weekend plans", description: "Was ist geplant, wann und mit wem?" },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a phone call making an appointment", description: "Termin vereinbaren am Telefon." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a public transport announcement", description: "Gleis, Verspätung, nächster Halt." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone describing their daily routine", description: "Tagesablauf in der richtigen Reihenfolge." },
  { level: "a1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a short dialogue about family", description: "Familienmitglieder und ihre Beziehungen." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short self-introduction text", description: "Name, Alter, Herkunft, Beruf." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a simple family description", description: "Wer gehört zur Familie und wie alt sind sie?" },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a shopping receipt and price list", description: "Was wurde gekauft, wie viel hat es gekostet?" },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a weather report", description: "Temperatur, Regen, Sonne, Wind." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short café menu", description: "Speisen, Getränke, Preise." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a public transport timetable", description: "Abfahrtszeiten, Gleise, Verbindungen." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a simple map with directions", description: "Den Weg auf einer Karte verstehen." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short text about someone's daily routine", description: "Tagesablauf — Reihenfolge der Aktivitäten." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a simple job advertisement", description: "Beruf, Anforderungen, Kontakt." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short note or postcard", description: "Anrede, kurze Nachricht, Gruß." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a doctor's appointment confirmation", description: "Datum, Uhrzeit, Praxis." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a simple recipe", description: "Zutaten und Schritte in Reihenfolge." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short diary entry", description: "Was ist gestern passiert?" },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a clothing store advertisement", description: "Kleidung, Größen, Preise, Angebote." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short biography", description: "Wichtigste Fakten über eine Person." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a text about hobbies", description: "Was machen die Personen gern und warum?" },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a simple invitation", description: "Wann, wo, wozu wird eingeladen?" },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short weekend-plan text", description: "Was ist wann geplant?" },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a pharmacy medicine label", description: "Dosierung und Anwendungshinweise verstehen." },
  { level: "a1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a simple form to understand what's required", description: "Welche Angaben werden verlangt?" },

  // ════════════════════ A2 ════════════════════
  // ── grammar ──
  { level: "a2", category: "grammar", skill: "grammar", theme: "Dative case", title: "Dative articles", description: "dem, der, dem, den (+n); einem/einer." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Dative case", title: "Dative pronouns", description: "mir, dir, ihm, ihr, uns, euch, ihnen." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Dative case", title: "Verbs with dative", description: "helfen, danken, gefallen, gehören, schmecken." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Dative case", title: "Dative prepositions", description: "aus, bei, mit, nach, seit, von, zu." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Two-way prepositions", title: "wo? + dative", description: "Location: Die Katze sitzt auf dem Tisch." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Two-way prepositions", title: "wohin? + accusative", description: "Movement: Ich gehe ins Kino." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Two-way prepositions", title: "Position verbs", description: "stellen/stehen, legen/liegen, setzen/sitzen, hängen." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Past tenses", title: "Irregular participles", description: "gegessen, getrunken, genommen, geschrieben…" },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Past tenses", title: "Participles of separable & -ieren verbs", description: "eingekauft, angerufen; studiert (no ge-)." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Past tenses", title: "haben or sein?", description: "Movement & change verbs take sein." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Past tenses", title: "Präteritum of modals", description: "konnte, musste, wollte, durfte, sollte." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Comparison", title: "Comparative", description: "größer als, lieber, besser, mehr." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Comparison", title: "Superlative", description: "am größten, am liebsten, der/die/das beste." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Comparison", title: "so … wie / als", description: "Equality vs. difference." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Adjective endings", title: "After definite articles", description: "der große Mann, das kleine Kind." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Adjective endings", title: "After indefinite articles", description: "ein großer Mann, eine kleine Wohnung." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Subordinate clauses", title: "weil & denn", description: "Reasons — verb-end vs. position 2." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Subordinate clauses", title: "dass-clauses", description: "Ich glaube, dass …" },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Subordinate clauses", title: "wenn-clauses", description: "Conditions and repeated time." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Subordinate clauses", title: "Main-clause connectors", description: "deshalb, trotzdem, dann, außerdem." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Reflexive verbs", title: "Accusative reflexives", description: "sich freuen, sich treffen, sich anmelden." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Reflexive verbs", title: "Dative reflexives", description: "Ich wasche mir die Hände." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Verbs with prepositions", title: "Common verb + preposition pairs", description: "warten auf, sich interessieren für, denken an." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Polite & future forms", title: "würde, könnte, hätte", description: "Polite requests and wishes." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Polite & future forms", title: "Future with werden", description: "Pläne und Vorhersagen." },
  { level: "a2", category: "grammar", skill: "grammar", theme: "Genitive (intro)", title: "Recognizing the genitive", description: "des Mannes, wegen des Wetters — recognition first." },

  // ── vocab themes ──
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Education & work", title: "School & courses", description: "Schulsystem, Kurse, Prüfungen, Noten." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Education & work", title: "Office life", description: "Kollegen, Aufgaben, Termine, Besprechungen." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Education & work", title: "Working conditions", description: "Vollzeit/Teilzeit, Überstunden, Urlaub, Gehalt." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Health", title: "At the doctor", description: "Symptome, Untersuchung, Rezept." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Health", title: "Pharmacy & medicine", description: "Apotheke, Medikamente, Dosierung." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Health", title: "Krankmeldung & insurance basics", description: "Krankschreibung, Versichertenkarte." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Housing", title: "Apartment search", description: "Anzeigen, Besichtigung, Vermieter." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Housing", title: "Rent & costs", description: "Kaltmiete, Nebenkosten, Kaution." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Housing", title: "Moving & living together", description: "Umzug, Nachbarn, Hausordnung." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Money & services", title: "Banking", description: "Konto eröffnen, überweisen, Karte, Gebühren." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Money & services", title: "Offices & paperwork", description: "Formulare, Unterlagen, Termin beim Amt, Bescheid." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Media & technology", title: "Phone & internet", description: "Handy, Apps, E-Mails, WLAN." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Feelings & opinions", title: "Expressing feelings", description: "froh, ärgerlich, enttäuscht, zufrieden." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Feelings & opinions", title: "Giving opinions", description: "Ich finde/glaube/meine, dass …" },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Social life", title: "Invitations & celebrations", description: "einladen, zusagen/absagen, Feste, Geschenke." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Social life", title: "Eating out", description: "Reservierung, Speisekarte, reklamieren, Trinkgeld." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Travel & environment", title: "Holidays & booking", description: "Hotel, buchen, Sehenswürdigkeiten." },
  { level: "a2", category: "vocab_theme", skill: "vocab", theme: "Travel & environment", title: "Nature & recycling", description: "Landschaft, Wetter extremes, Mülltrennung." },

  // ── skills ──
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Phone conversations", description: "Anrufen, verbinden, Nachricht hinterlassen." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your past", description: "Wochenende, Urlaub, Lebenslauf im Perfekt." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Doctor's appointment", description: "Symptome beschreiben, Empfehlungen verstehen." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Apartment viewing", description: "Fragen zu Miete, Kaution, Übergabe." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Make plans together", description: "Vorschlagen, zustimmen, ablehnen, verschieben." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Semi-formal emails", description: "Anfrage, Entschuldigung, Terminverschiebung." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Short reports of events", description: "Was ist passiert? — im Perfekt schreiben." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Ads & short articles", description: "Anzeigen, Aushänge, kurze Zeitungstexte." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Everyday conversations", description: "Detailinformationen aus Gesprächen." },
  { level: "a2", category: "skill", skill: "reading", theme: "Exam prep", title: "Goethe A2 task types", description: "Every module's format." },
  { level: "a2", category: "skill", skill: "writing", theme: "Exam prep", title: "One full A2 Modellsatz", description: "Under exam timing." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Compare two things or people", description: "größer als, genauso … wie, am besten." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Describe your ideal apartment", description: "Zimmer, Lage, Miete — Wünsche formulieren." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your typical work day", description: "Kollegen, Aufgaben, Termine." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss your feelings about something", description: "Ich fühle mich …, weil …" },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Give your opinion on a topic", description: "Ich finde/glaube/meine, dass …" },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about a weekend trip", description: "Wohin, wie lange, was hast du gemacht?" },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Explain a problem to a landlord", description: "Etwas ist kaputt; um Reparatur bitten." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about banking and paying bills", description: "Konto, überweisen, Gebühren." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Invite someone to a celebration", description: "einladen, zusagen, absagen." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss recycling and the environment", description: "Mülltrennung, Umweltschutz." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your favorite restaurant", description: "Speisekarte, reservieren, empfehlen." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Describe symptoms and ask for medicine", description: "In der Apotheke — Beschwerden erklären." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your commute and transport options", description: "Bus, Bahn, Fahrrad — Vor- und Nachteile." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Explain what you did last year", description: "Präteritum von Modalverben und sein/haben." },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Give advice using würde/sollte", description: "An deiner Stelle würde ich …" },
  { level: "a2", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about household chores and furniture", description: "putzen, aufräumen, Möbel beschreiben." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write an email requesting information", description: "Anfrage — höflich formulieren." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write an apology email for missing an appointment", description: "Entschuldigung, Grund, neuer Vorschlag." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write about your work day", description: "Office life — Aufgaben und Termine." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write a short report about a doctor's visit", description: "Symptome, Diagnose, Rezept." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write an apartment-search inquiry email", description: "Anzeige, Besichtigungstermin erfragen." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write about your feelings on a recent event", description: "Ich war …, weil …" },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Give your written opinion on a topic", description: "Meiner Meinung nach …" },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write a short travel account", description: "Wohin, wie lange, was war schön?" },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write a complaint email about a service", description: "Problem beschreiben, Lösung fordern." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write an invitation to a celebration", description: "Wann, wo, wozu — freundlicher Ton." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write a description of your apartment", description: "Zimmer, Lage, was dir gefällt." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write about your typical week including work", description: "Arbeitszeiten und Freizeit kombinieren." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write a short comparison of two options", description: "Vorteile und Nachteile gegenüberstellen." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write a note explaining a household problem", description: "Was ist kaputt? Was brauchst du?" },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write about paying a bill or opening an account", description: "Bank, Überweisung, Gebühren." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write a short text about recycling habits", description: "Mülltrennung zu Hause beschreiben." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write about a memorable event from last year", description: "Präteritum und Perfekt kombinieren." },
  { level: "a2", category: "skill", skill: "writing", theme: "Writing", title: "Write a message accepting or declining an invitation", description: "Gern! / Leider kann ich nicht, weil …" },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a phone conversation", description: "Grund des Anrufs erfassen." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone talking about their past", description: "Perfekt/Präteritum im Kontext." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a doctor's appointment", description: "Symptome und Empfehlungen verstehen." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to an apartment viewing conversation", description: "Miete, Kaution, Zustand der Wohnung." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to people making plans", description: "Vorschlagen, zustimmen, ablehnen." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone comparing two things", description: "Komparativ und Superlativ erkennen." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a conversation about work", description: "Aufgaben, Kollegen, Probleme." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone expressing feelings", description: "Gefühle und ihre Gründe erfassen." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to an opinion discussion", description: "Wer sagt was und warum?" },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a travel or holiday conversation", description: "Reiseziel, Dauer, Highlights." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a complaint at a shop or restaurant", description: "Problem und geforderte Lösung." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to an invitation being made", description: "Wann, wo, wozu wird eingeladen?" },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a description of an apartment", description: "Zimmer, Lage, Ausstattung." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a banking conversation", description: "Konto, Überweisung, Gebühren." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a conversation about recycling", description: "Mülltrennung erklärt bekommen." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone narrating last year's events", description: "Ereignisse in der richtigen Reihenfolge." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a radio advertisement", description: "Angebot, Preis, Kontakt." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a conversation about household chores", description: "Wer macht was im Haushalt?" },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone requesting information by phone", description: "Frage und Antwort erfassen." },
  { level: "a2", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to people discussing weekend plans", description: "Was ist geplant, wann und mit wem?" },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a semi-formal email", description: "Anrede, Anliegen, Gruß." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short apartment listing", description: "Miete, Zimmer, Lage." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a doctor's note", description: "Diagnose und Empfehlung verstehen." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a bank statement or account summary", description: "Ein- und Ausgänge, Gebühren." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short news article", description: "Hauptinformationen entnehmen." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read an opinion column", description: "Standpunkt des Autors erkennen." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a travel brochure", description: "Angebot, Preis, Sehenswürdigkeiten." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a complaint letter", description: "Problem und geforderte Lösung erkennen." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read an invitation", description: "Wann, wo, wozu wird eingeladen?" },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a report of a past event", description: "Chronologie mit Perfekt/Präteritum." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a comparison of two products", description: "Vorteile und Nachteile identifizieren." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a recycling guide", description: "Was gehört in welche Tonne?" },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a work schedule", description: "Termine und Zuständigkeiten." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short biography covering the past", description: "Lebenslauf im Perfekt/Präteritum." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a restaurant review", description: "Meinung und Begründung erkennen." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a housing contract excerpt", description: "Kaltmiete, Nebenkosten, Kündigungsfrist." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a phone or internet contract", description: "Laufzeit, Kosten, Kündigung." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a short story about feelings", description: "Gefühle und ihre Ursachen erkennen." },
  { level: "a2", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a public notice about weather warnings", description: "Wichtige Informationen herausfiltern." },

  // ════════════════════ B1 ════════════════════
  // ── grammar ──
  { level: "b1", category: "grammar", skill: "grammar", theme: "Adjective declension", title: "All cases with definite articles", description: "Incl. genitive." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Adjective declension", title: "All cases with indefinite & no article", description: "ein alter Freund; frisches Brot." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Narrative past", title: "Präteritum: regular verbs", description: "machte, lernte, arbeitete." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Narrative past", title: "Präteritum: irregular & mixed verbs", description: "ging, kam, wusste, brachte, dachte." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Narrative past", title: "Plusquamperfekt", description: "hatte/war + Partizip II." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Narrative past", title: "nachdem, als, während", description: "Tense sequence in time clauses." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Passive voice", title: "Present & past passive", description: "wird gebaut / wurde gebaut." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Passive voice", title: "Passive with modals", description: "muss eingereicht werden." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Passive voice", title: "Agent with von / durch", description: "And when to drop it." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Konjunktiv II", title: "wäre, hätte, würde, könnte", description: "Forms and polite use." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Konjunktiv II", title: "Unreal conditions (present)", description: "Wenn ich Zeit hätte, würde ich …" },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Konjunktiv II", title: "Unreal conditions (past)", description: "Wenn ich das gewusst hätte, wäre ich …" },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Konjunktiv II", title: "Wishes & advice", description: "Ich wünschte …; An deiner Stelle würde ich …" },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Relative clauses", title: "Nominative, accusative & dative", description: "der/den/dem, die/die/der, das/das/dem." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Relative clauses", title: "Genitive: dessen / deren", description: "Die Frau, deren Auto …" },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Relative clauses", title: "With prepositions", description: "Die Kollegin, mit der ich arbeite." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Infinitive clauses", title: "Infinitive with zu", description: "Es ist wichtig, … zu …; vergessen zu …" },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Infinitive clauses", title: "um / statt / ohne … zu", description: "Purpose and contrast constructions." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Connectors", title: "obwohl & trotzdem", description: "Concession, both word orders." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Connectors", title: "damit & sodass", description: "Purpose vs. result; damit vs. um…zu." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Connectors", title: "je … desto", description: "Je mehr ich lerne, desto besser …" },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Connectors", title: "Two-part connectors", description: "entweder…oder, weder…noch, sowohl…als auch." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Indirect speech & questions", title: "Indirect questions", description: "Ich weiß nicht, ob/wann/warum …" },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Indirect speech & questions", title: "Reporting statements", description: "Er sagt, dass …; Präsens vs. Konjunktiv I awareness." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Genitive", title: "Genitive forms", description: "des Mannes, der Frau, meines Bruders." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Genitive", title: "Genitive prepositions", description: "wegen, trotz, während, innerhalb, außerhalb." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Special noun & verb forms", title: "n-declension", description: "der Kunde/den Kunden, der Name, der Kollege." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Special noun & verb forms", title: "Pronominal adverbs", description: "darauf, damit, worüber — with fixed prepositions." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Special noun & verb forms", title: "Participles as adjectives", description: "die lachenden Kinder, das reparierte Auto." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Word order", title: "TeKaMoLo", description: "Temporal – kausal – modal – lokal in the Mittelfeld." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Word order", title: "Pronoun order", description: "Accusative before dative pronoun: Ich gebe es ihm." },
  { level: "b1", category: "grammar", skill: "grammar", theme: "Future", title: "Futur I & II", description: "Pläne, Vermutungen: Er wird wohl … sein." },

  // ── vocab themes ──
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Applications & Ausbildung", title: "Bewerbung vocabulary", description: "Anschreiben, Lebenslauf, Zeugnis, Vorstellungsgespräch." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Applications & Ausbildung", title: "The dual training system", description: "Berufsschule, Betrieb, IHK, Ausbildungsvertrag, Vergütung." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Applications & Ausbildung", title: "Rights & duties as an Azubi", description: "Probezeit, Urlaub, Berichtsheft, Abschlussprüfung." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Bureaucracy", title: "Amtsdeutsch survival kit", description: "Antrag, Frist, Bescheid, Widerspruch, Nachweis." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Bureaucracy", title: "Visa & residence", description: "Aufenthaltstitel, Anmeldung, Sperrkonto, VIDEX." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Bureaucracy", title: "Contracts & insurance", description: "Krankenversicherung, Haftpflicht, kündigen, Klauseln." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Working life", title: "Workplace communication", description: "Anweisungen, Feedback, Konflikte, Small Talk." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Working life", title: "Money & taxes", description: "brutto/netto, Steuerklasse, Gehaltsabrechnung." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Health & society", title: "The health system", description: "Hausarzt, Facharzt, Überweisung, Vorsorge." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Health & society", title: "Environment & sustainability", description: "Umweltschutz, Energie, Nachhaltigkeit." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Health & society", title: "News & politics basics", description: "Schlagzeilen, Wahlen, Parteien, Meinungsfreiheit." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Digital life", title: "Media & data", description: "Datenschutz, soziale Medien, Online-Dienste." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Culture & integration", title: "Living in Germany", description: "Traditionen, Feiertage, interkulturelle Situationen." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Culture & integration", title: "Mobility", description: "ÖPNV-Abos, Führerschein, Deutschlandticket, Umzug." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Argumentation", title: "Opinion phrases", description: "Meiner Meinung nach, einerseits/andererseits, im Gegensatz dazu." },
  { level: "b1", category: "vocab_theme", skill: "vocab", theme: "Argumentation", title: "Agreeing & disagreeing", description: "Da stimme ich zu / Da bin ich anderer Meinung, weil …" },

  // ── skills ──
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Job interview practice", description: "Stärken, Schwächen, Werdegang, Rückfragen." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Give a short presentation", description: "Goethe B1 Sprechen Teil 2: Thema strukturiert vorstellen." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss & defend an opinion", description: "Argumentieren, widersprechen, Kompromisse finden." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Phone calls with offices", description: "Auskünfte einholen, Probleme klären, Termine verschieben." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Formal letters & emails", description: "Bewerbung, Beschwerde, Kündigung — Aufbau + feste Wendungen." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Forum posts & opinions", description: "Goethe B1 Schreiben Teil 2 style." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Radio & TV news", description: "Hauptinformationen aus Nachrichten entnehmen." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Summarize articles", description: "Kernaussagen mündlich und schriftlich wiedergeben." },
  { level: "b1", category: "skill", skill: "reading", theme: "Exam prep", title: "Goethe B1 task types", description: "Every module — the B1 exam is modular; know each cold." },
  { level: "b1", category: "skill", skill: "writing", theme: "Exam prep", title: "One full B1 Modellsatz", description: "Under exam timing." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Tell a travel story", description: "Präteritum und Plusquamperfekt im Erzählfluss." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss an academic or work-related article", description: "Kernaussagen zusammenfassen und kommentieren." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your life goals and plans", description: "Zukunftspläne mit werden und Konjunktiv II." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss a film, book or piece of media", description: "Handlung zusammenfassen, Meinung äußern." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Debate a controversial topic", description: "Argumentieren und widersprechen." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Explain a workplace conflict and its resolution", description: "Konflikt schildern, Lösung vorschlagen." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your Ausbildung and training program", description: "Berufsschule, Betrieb, IHK." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss your rights and duties as an Azubi", description: "Probezeit, Urlaub, Berichtsheft." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Explain a bureaucratic process to someone", description: "Antrag, Frist, Bescheid — Schritt für Schritt." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your health and the healthcare system", description: "Hausarzt, Facharzt, Überweisung." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss environmental issues", description: "Umweltschutz, Nachhaltigkeit, Energie." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Give advice using Konjunktiv II", description: "An deiner Stelle würde ich …" },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Describe a hypothetical situation", description: "Wenn ich … hätte, würde ich …" },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Narrate a story using different past tenses", description: "Präteritum, Perfekt und Plusquamperfekt kombinieren." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Argue for and against an idea", description: "Einerseits … andererseits …" },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about news and current events", description: "Schlagzeilen zusammenfassen und kommentieren." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Discuss integration and living in Germany", description: "Traditionen, Feiertage, interkulturelle Situationen." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Explain a contract or insurance policy", description: "Krankenversicherung, Haftpflicht, Klauseln." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Talk about your taxes and salary", description: "brutto/netto, Steuerklasse." },
  { level: "b1", category: "skill", skill: "speaking", theme: "Speaking", title: "Give a structured opinion using connectors", description: "obwohl, trotzdem, damit, je … desto." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a formal complaint letter", description: "Problem, Forderung, höflicher Ton." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a job application cover letter", description: "Anschreiben — Aufbau und feste Wendungen." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a report on a work-related incident", description: "Was ist passiert, wer war beteiligt?" },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write an essay discussing pros and cons", description: "Einerseits/andererseits, Fazit." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a summary of a news article", description: "Kernaussagen in eigenen Worten." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write about your life goals", description: "Zukunftspläne strukturiert darstellen." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a review of a film or book", description: "Handlung, Meinung, Empfehlung." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a forum post debating a topic", description: "Goethe B1 Schreiben Teil 2 style." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a formal email to a Behörde", description: "Anliegen klar und höflich formulieren." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write about your Ausbildung experience", description: "Betrieb, Aufgaben, was du gelernt hast." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a letter explaining a bureaucratic issue", description: "Antrag, Frist, Widerspruch." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write about environmental responsibility", description: "Nachhaltigkeit im Alltag." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a short story using Konjunktiv II", description: "Wenn ich … hätte, würde ich …" },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write an account of a past event using Plusquamperfekt", description: "Was war schon passiert, bevor …?" },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a persuasive text using connectors", description: "obwohl, trotzdem, deshalb, außerdem." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write about workplace communication challenges", description: "Feedback, Konflikte, Missverständnisse." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a formal cancellation letter", description: "Vertrag, Kündigungsfrist, Grund." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write about integration and culture", description: "Traditionen, Feiertage, eigene Erfahrungen." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a text discussing health and society", description: "Gesundheitssystem, Vorsorge." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write about digital life and data privacy", description: "Datenschutz, soziale Medien." },
  { level: "b1", category: "skill", skill: "writing", theme: "Writing", title: "Write a text using indirect speech to report what someone said", description: "Er sagt, dass … / Sie meinte, …" },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a travel story", description: "Chronologie mit Präteritum/Plusquamperfekt." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to an academic-style talk", description: "Hauptthesen und Beispiele erfassen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a discussion about life goals", description: "Pläne und Begründungen verstehen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a film or media review", description: "Meinung und Argumente des Sprechers." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a debate", description: "Positionen beider Seiten unterscheiden." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a workplace conflict conversation", description: "Problem und vorgeschlagene Lösung." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to an interview about an Ausbildung", description: "Betrieb, Aufgaben, Erfahrungen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a discussion of rights and duties", description: "Probezeit, Urlaub, Pflichten." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a bureaucratic phone call", description: "Antrag, Frist, benötigte Unterlagen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a doctor discussing the healthcare system", description: "Hausarzt, Facharzt, Überweisung." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to an environmental discussion", description: "Argumente für und gegen Maßnahmen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone giving advice", description: "Konjunktiv-II-Formen im Kontext erkennen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone describing a hypothetical situation", description: "Wenn … dann … — Bedingungssätze." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a story told in the past tense", description: "Präteritum, Perfekt, Plusquamperfekt unterscheiden." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to an argument for and against something", description: "Pro- und Contra-Argumente trennen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a news report", description: "Hauptinformationen aus Nachrichten." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a discussion about integration", description: "Erfahrungen und Meinungen erfassen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to someone explaining a contract", description: "Bedingungen und Kündigungsfristen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a conversation about taxes and salary", description: "brutto/netto, Steuerklasse, Abzüge." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a structured opinion piece", description: "Konnektoren wie obwohl, trotzdem, damit erkennen." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a formal phone call with an office", description: "Anliegen, benötigte Unterlagen, nächste Schritte." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a podcast about digital life", description: "Datenschutz, soziale Medien, Online-Dienste." },
  { level: "b1", category: "skill", skill: "listening", theme: "Listening & reading", title: "Listen to a panel discussion", description: "Mehrere Sprecher und ihre Standpunkte." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a travel blog entry", description: "Chronologie und persönliche Eindrücke." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read an academic-style article", description: "Thesen, Argumente, Beispiele erkennen." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a text about life goals", description: "Pläne und Begründungen verstehen." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a film or book review", description: "Meinung und Argumente des Autors." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a debate or opinion-forum thread", description: "Verschiedene Standpunkte unterscheiden." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read about a workplace conflict case study", description: "Problem und Lösung nachvollziehen." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read about the dual training (Ausbildung) system", description: "Berufsschule, Betrieb, IHK, Vergütung." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read about Azubi rights and duties", description: "Probezeit, Urlaub, Berichtsheft, Abschlussprüfung." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a Bescheid or official notice", description: "Amtsdeutsch: Frist, Widerspruch, Nachweis." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a health-system explainer", description: "Hausarzt, Facharzt, Vorsorge." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read an environmental-policy article", description: "Maßnahmen und ihre Begründung." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a text with Konjunktiv II (advice or wishes)", description: "Ich wünschte …; An deiner Stelle …" },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a narrative using Plusquamperfekt", description: "Was war schon passiert, bevor …?" },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a persuasive essay", description: "Argumentationsstruktur erkennen." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read an article about workplace communication", description: "Anweisungen, Feedback, Konflikte." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a rental or insurance contract", description: "Bedingungen, Kündigungsfristen, Klauseln." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a text about integration and living in Germany", description: "Traditionen, interkulturelle Situationen." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a data-privacy notice", description: "Datenschutz-Begriffe verstehen." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a news article about taxes or salary", description: "brutto/netto, Steuerklasse, Abzüge." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read an opinion piece with connectors", description: "obwohl, trotzdem, je … desto." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read an interview transcript", description: "Fragen und Antworten, indirekte Rede." },
  { level: "b1", category: "skill", skill: "reading", theme: "Listening & reading", title: "Read a formal letter example", description: "Aufbau und feste Wendungen erkennen." },
];
